# Generated by Django 5.0.2 on 2025-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsystem', '0008_consultation_symptom_onset_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='tpa_approval_notes',
            field=models.TextField(blank=True, verbose_name='TPA Approval Notes'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tpa_approved',
            field=models.BooleanField(default=False, verbose_name='TPA Approved'),
        ),
    ]
