# Generated by Django 5.0.2 on 2025-05-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsystem', '0009_consultation_tpa_approval_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ct_scans/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_scan_images', to='patientsystem.patient')),
            ],
        ),
    ]
